### ISSUE TITLE
Unable to load "zoo_loader.cgi"

### ISSUE THREAD

**Issue by MlFiras** [mapmint/mapmint#14]
Hello, I installed the OSGeoLive 12.0 in order to install Mapmint. the installation of Mapmint was successful and without errors.
I tried most of mapmint tools and they worked perfectly but in the "**Publisher**" I managed to publish my project and it indicates that the project is saved
![2019-03-19-105926_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54597052-26229200-4a36-11e9-9a06-246f821f2533.png)

 but when I click on the "**Publish Map Preview**" I get an error.
![2019-03-19-105940_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54597078-33d81780-4a36-11e9-8eda-c1756b19abab.png)

I tried to find the problem with the google chrome consol and I found that the "**zoo_loader.cgi**" is causing the problem with a message "**Failed to load resource: the server responded with a status of 501 (Not Implemented)**"
![2019-03-19-105953_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54597087-39356200-4a36-11e9-8d17-2d2aa61903f9.png)

I opened the file "**zoo_loader.cgi**"
![2019-03-19-110314_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54597498-f4f69180-4a36-11e9-8aea-3aeab5f56464.png)

and I found that if I add this line to the url "**?Request=GetCapabilities&Service=WPS** " I get all the capabilities of "**zoo_loader.cgi**"
![2019-03-19-110614_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54597545-063f9e00-4a37-11e9-9e74-223c7a91ec0b.png)

**What should I do in this situation ?**

Thank you !

**Comment by gfenoy** [comment]
Sorry for this issue.

It looks like the ``path`` parameter from the ``[oo]`` section of your ``main.cfg`` file is not set properly. It should point to an existing python distributed with LibreOffice. For instance, if you use LibreOffice version 5.3, then your path should be set to: ``/opt/libreoffice5.3/program/python``.

Note that once you will have defined the correct path in your ``main.cfg`` file, you will have to verify that the LibreOffice server is running. For this, you can run the following command: 

``netstat -na | grep "LISTEN " | grep 3662``

In case you have a result, then it means the LibreOffice server is running and you are ready to use it from MapMint. In other cases, you should start it by using the following command: 

``sudo /etc/init.d/mapmint-libreoffice-server start``

Also, note that the publication of the Project preview is optional. It simply uses LibreOffice to produce a pdf file converted into png file to display in the home page. In case this preview does not exist, then a WMS GetMap request will be used.

I hope it helps.

**Comment by MlFiras** [comment]
Thank you for you response. I did what you told me to do and it gave another error, but I Have another concern now, which is about the "**Preview**" page.

I get an error like this:

![2019-03-19-174056_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54624703-2e96bf00-4a6e-11e9-8cc9-d3548fb52ffe.png)

Thank you in advance

**Comment by gfenoy** [comment]
Sorry for this issue.

I guess that there is something wrong in the setting you have made before your publication. Is it possible that you did not select any default Base Layer?

Also, on your first publication you should make sure to select "None" for "Created layers" in the "Base Layers" panel accessible from the "Layers" panel (as shown in the following screenshot).

<img width="1040" alt="Capture d'écran 2019-03-20 10 25 33" src="https://user-images.githubusercontent.com/1606022/54673496-a90d2080-4afa-11e9-85f1-729cf6dbc354.png">

I hope this solves your issue.

**Comment by MlFiras** [comment]
Thank you for your solution but it doesn't work. 
Can you please mention the versions of Mapmint, MapServer, Zoo-project and GDAL that you are using and on which Linux version they are installed ? 

Thank you for you time !!

**Comment by gfenoy** [comment]
Sorry for I think my guess was wrong. 

I use MapMint on different kind of server from MacOS to GNU/Linux (mainly Gentoo, Debian and Ubuntu). Nevertheless, for demonstration purpose, I have setup a server specifically using OSGeoLive 12.0 like the one you are using, you can see in the screenshot below the versions of the used softwares.

<img width="351" alt="Capture d'écran 2019-03-21 10 23 03" src="https://user-images.githubusercontent.com/1606022/54743043-551a3e80-4bc3-11e9-8d15-6406897ff68c.png">

Anyway, I have noted that it is question of the template preview/toolbar_bs.tmpl in the message. So maybe you should check what are your settings in the Services panel. In case you don't want one toolbar, then you should select "None" int the select lit like shown below.
<img width="821" alt="Capture d'écran 2019-03-21 10 26 03" src="https://user-images.githubusercontent.com/1606022/54743171-be9a4d00-4bc3-11e9-8cf2-5cfede9d59f3.png">

I hope it helps to solve your issue.

**Comment by MlFiras** [comment]
that didn't work also.
Is there any differences between the installation guide in the [wokshops repository](https://github.com/mapmint/workshops) ([introduction.txt](https://github.com/mapmint/workshops/blob/master/MapMint/2018/introduction.txt)) and the installation guide in [mapmint repository](https://github.com/mapmint/mapmint), [(INSTALL.md)](https://github.com/mapmint/mapmint/blob/master/INSTALL.md) ?

I managed to install mapmint with the guide in the workshop and with other guide, I got many errors during the installation.

**Comment by gfenoy** [comment]
The workshop material is the more up-to-date installation guide, it can also be viewed from [here](https://mapmint.github.io/workshops/MapMint/2018/).

Can you please show every panel from your Publisher to see if anything is wrong there?

**Comment by gfenoy** [comment]
I can also add this materials: 
 * [user guide in french](http://mapmint.github.io/userguide-fr/introduction/installmapmint.html)
 * [user guide in english](http://mapmint.github.io/userguide-fr/en/introduction/installmapmint.html)

But the installation steps are for old ubuntu version... 

There is also [this workshop material](https://mapmint.github.io/workshops/MapMint4ME/2019/) but it is specific to MapMint4ME.

**Comment by MlFiras** [comment]
Thank you for the guide.
in the Preview page I got another error indicating that **'/home/src/mapmint/mapmint-ui/templates/preview/modules/style/templates.html'** is missing.
here's a screenshot:
![2019-03-22-080826_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54806251-c0bee300-4c79-11e9-83ac-3bc8dc66dfe5.png)

**Comment by gfenoy** [comment]
Hi, 
thanks a lot for your feedbacks, the full directory tempaltes/preview/module/style itself is not present in github repository. Note that I have just checked on some production servers and this directory is not present either there but does not cause any issue.

 I think you have selected a module that is not needed to get the application running properly. So, may I ask you to please share the Services panel of your Publisher here, I am sure we can figure out what is the module that cause the issue. But I am guessing that it comes from the "Add Layer" module. Note that this module is probably not yet usable on your setup as you need to create a specific Overlays project for being able to activate it. Anyway, let start by providing your current Services panel and check if there is any issue with the selected module.

Note also that you may try activating no module, then activate one by one to see from which service the issue comes from.

I hope this helps.

**Comment by MlFiras** [comment]
Hello, thank you for your answer.
as you asked, **the services panel:**
![2019-03-25-095210_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54906648-0c74c500-4ee4-11e9-82c8-fce62c68575e.png)
I suggest that you take a look on the other panels also, if you don't mind.

**Geneal** Panel:
![2019-03-25-095205_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54906921-a63c7200-4ee4-11e9-9fdf-885c4b3f07e3.png)

**Layers/Base Layers** Panel:
![2019-03-25-095207_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54906928-aa688f80-4ee4-11e9-8527-d28cb6dee44f.png)

**Layers/Overlay Layers** Panel:
![2019-03-25-095746_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54906959-b8b6ab80-4ee4-11e9-84c2-60265202ac14.png)

**Map** Panel:
![2019-03-25-095209_1920x1080_scrot](https://user-images.githubusercontent.com/46325858/54906966-bf452300-4ee4-11e9-8efa-0ffb659d7cfc.png)

**Let me know if you notice anything wrong. Thank you !**

**Comment by gfenoy** [comment]
Hello,
sorry for late reply.

From what I see from your Publisher everything looks fine in the configuration you have made.

The issue about the missing file can be solved simply by running the following command from yoru server:

` sudo mkdir /home/src/mapmint/mapmint-ui/templates/preview/modules/style ; sudo touch /home/src/mapmint/mapmint-ui/templates/preview/modules/style/templates.tmpl `

Note that this file was missing from the GitHub repository but, this is now available. So you can simply download the latest updated files by using `git pull` from your `/home/src/mapmint` directory.  

I have taken advantage of this commit to commit also few other things such as the modules support where people can implement their own WPS services and integrate them int the published MapMint Client applications.

Anyway, I hope this will solve your issue and you will be able to preview your project.

**Comment by MlFiras** [comment]
Thanks !!, it works perfectly now.
I also reinstalled mapmint to see if the problem occures again and it did not.

I suggest that you change the name of **e1071_1.7-0.1.tar.gz** to **e1071_1.7-1.tar.gz** located in `/mm-install/mapmint-setup/osgeolive/dependencies/tasks/r-cran.yml`
 you can see here that the link doesn't work anymore ([e1071_1.7-0.1.tar.gz](https://cran.r-project.org/src/contrib/e1071_1.7-0.1.tar.gz))

**Comment by gfenoy** [comment]
Thanks for your message, the required changes have been committed in ansible-role for the OSGeoLive target.
