### ISSUE TITLE
Passwords stored in plain text?

### ISSUE THREAD

**Issue by milovanderlinden** [mapmint/mapmint#3]
Looking at the source code I think I can conclude that passwords are stored in plain text. This is bad practice. Wouldn't it be better to use some form of hashing and/or salting on the password field when it gets stored in the database?

**Comment by gfenoy** [comment]
If you review this part of the code https://github.com/mapmint/mapmint/blob/master/mapmint-services/authenticate/service.py#L298 you should conclude that the password are encrypted.
